import React from 'react'
import "./featured.scss"
import MoreVertIcon from '@mui/icons-material/MoreVert';
import { CircularProgressbar } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';





const Featured = () => {
  return (
    <div className='featured'>
        <div className="top">
            <h1 className="title">Total Revenue</h1>
            <MoreVertIcon fontSize='small'/>
        </div>
        <div className="bottom">
            <div className="featuredChart">
                <CircularProgressbar value={65} text={`70%`} strokeWidth={4}/>
            </div>
            <p className="title">Total sales for the day</p>
            <p className="amount">$340</p>
            <p className="desc">This is buy selling the goods in the time period of 10/10/21 -10/11/21 and the revenue generated by cash sales. </p>
        
            <div className="summary">
                <div className="item">
                    <div className="itemTitle">Target</div>
                        <div className="itemResults negative">
                            <div className="resultsAmount">
                                <KeyboardArrowDownIcon fontSize='small'/>
                                 $15.6k
                            </div>
                        </div>
                </div>

                <div className="item">
                    <div className="itemTitle">Last week</div>
                        <div className="itemResults positive">
                            <div className="resultsAmount">
                                <KeyboardArrowUpIcon fontSize='small'/>
                                 $15.6k
                            </div>
                        </div>
                </div>


                <div className="item">
                    <div className="itemTitle">Last Month</div>
                        <div className="itemResults positive">
                            <div className="resultsAmount">
                                <KeyboardArrowUpIcon fontSize='small'/>
                                 $15.6k
                            </div>
                        </div>
                </div>

                
            </div>
        </div>
    </div>
  )
}

export default Featured